version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.0.0
      - image: deangiberson/aws-dynamodb-local:2017-03-08
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-${{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create db
          command: npm run create-db
      - run:
          name: Setup db
          command: npm run populate-db
      - run: mkdir junit
      - run:
          name: Test
          command: npm run test-ci
          environment:
            TEST_REPORT_PATH: junit
      - store_artifacts:
          path: ./junit
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./junit
  deploy_dev:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: 
          name: Get commit message
          command: echo 'export TF_VAR_deployment_description=`git log --format=oneline -n 1 $CIRCLE_SHA1` >> $BASH_ENV
      - run:
          name: Install Apex
          command: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      - run:
          name: Install node
          command: apk add --update nodejs nodejs-npm
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-${{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Apex deploy
          command: apex deploy -r ap-northeast-1
      - run:
          name: Apex init
          command: apex infra init
      - run:
          name: Apex get
          command: apex infra get
      - run:
          name: Apex plan
          command: apex infra plan
      - run:
          name: Apex apply
          command: apex infra apply
    #   - run:
    #       name: Create deployment
    #       command: aws apigateway create-deployment --rest-api-id 1234123412 --stage-name dev --description 'Second deployment to the dev stage'
workflows:
  version: 2
  test:
    jobs:
      - build
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: master
  # deploy:
  #   jobs:
  #     - deploy_dev