version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.0.0
      - image: deangiberson/aws-dynamodb-local:2017-03-08
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-${{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create db
          command: npm run create-db
      - run:
          name: Setup db
          command: npm run populate-db
      - run: mkdir junit
      - run:
          name: Test
          command: npm run test-ci
          environment:
            TEST_REPORT_PATH: junit
      - store_artifacts:
          path: ./junit
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./junit
  deploy_dev:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install Apex
          command: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      - run:
          name: Install node
          command: apk add --update nodejs
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Apex deploy
          command: apex deploy
      - run:
          name: Apex init
          command: apex infra init
      - run:
          name: Apex get
          command: apex infra get
      - run:
          name: Apex plan
          command: apex infra plan
      - run:
          name: Apex apply
          command: apex infra apply
workflows:
  version: 2
  # test:
  #   jobs:
  #     - build
  # build_and_deploy:
  #   jobs:
  #     - build
  #     - deploy_dev:
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only: master
  deploy:
    jobs:
      - deploy_dev