version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.0.0
      - image: deangiberson/aws-dynamodb-local:2017-03-08
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-${{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create db
          command: npm run create-db
      - run:
          name: Setup db
          command: npm run populate-db
      - run:
          name: Test
          command: npm run test-ci
      - store_artifacts:
          path: test-report.xml
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-report.xml
